import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';
import UserPreview from "../components/userResume";


export default function FoxyImage() {
  return (
    <div className='flex flex-col min-h-screen justify-between bg-fox-pattern'>
      <Head>
        <title>My Foxy Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex flex-col w-full items-center'>
       
        <section className='flex flex-col items-center justify-center my-28'>
          <div className='relative'>
            <h1 className='font-bold text-2xl mb-9 circle-decoration'>About Us</h1>
          </div>
          <p className='max-w-3xl text-xl'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus ac sodales lectus. Cras viverra et eros vulputate lacinia. Donec pulvinar, orci id auctor semper, augue nunc suscipit tortor.
          </p>
        </section>
        <section className='mt-6 flex flex-col items-center w-full max-w-5xl px-5'>
            <h2 className='text-2xl font-bold'>Members</h2>
            <UserPreview name="Alberto Munguia" tag="beto_munguia" role="Developer"/>
            <UserPreview name="Elizabeth Lopez" tag="elizabeth_lopez" role="Researcher" reverse={true}/>
            <UserPreview name="Francisco Millan" tag="francisco_millan" role="Developer"/>
            <UserPreview name="Gael Hurtado" tag="gael_hurtado" role="Developer"reverse={true}/>
            <UserPreview name="Diego Villalobos" tag="diego_villalobos" role="Developer"/>
        </section>
      </main>

      <Footer />
    </div>
  )
}
