import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';

import { FiFacebook, FiInstagram, FiDownload } from 'react-icons/fi';


export default function FoxyImage() {
  return (
    <div className='flex flex-col min-h-screen justify-between bg-fox-pattern'>
      <Head>
        <title>My Foxy Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex flex-col w-full items-center'>
        <div className='relative'>
          <h1 className='font-bold text-2xl mb-9 triangle-decoration'>MY FOXY IMAGE</h1>
        </div>
        <section className='flex flex-col gap-x-10 items-center justify-start'>
          <img width={300} src='https://images-assets.nasa.gov/image/PIA12229/PIA12229~thumb.jpg'/>
          <span>Original</span>
          <h2 className='font-bold text-3xl'>MY RANDOM TITLE</h2>

          <div className='flex flex-col gap-y-3 items-center mt-6'>
            <div className='flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-[#D1415A]'>
              <FiDownload size={27} />
              <span>DOWNLOAD</span>
            </div>
            <div className='flex flex-row gap-x-10'>
              <div className='flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500'>
                <FiInstagram size={27} />
                <span>SHARE</span>
              </div>
              <div className='flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-blue-500'>
                <FiFacebook size={27} />
                <span>SHARE</span>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
