import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';
import { useRouter } from 'next/router';

import { FiFacebook, FiInstagram, FiDownload } from 'react-icons/fi';
import { AiOutlineLoading3Quarters } from 'react-icons/ai';
import { useEffect, useState } from 'react';


export default function FoxyImage() {
  const router = useRouter();
  const [isLoading, setIsLoading] = useState(true);
  const [url, setUrl] = useState('')

  return (
    <div className='flex flex-col min-h-screen justify-between bg-fox-pattern'>
      <Head>
        <title>My Foxy Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex flex-col w-full items-center'>
        <div className='relative'>
          <h1 className='font-bold text-2xl mb-9 triangle-decoration'>MY FOXY IMAGE</h1>
        </div>
        <section className='flex flex-col gap-x-10 items-center justify-start px-1'>
          <div className='max-w-sm'>
            { router.query.q &&
              <img src={ 'http://127.0.0.1:5000/generateImage?key=' + router.query.q } onLoad={()=>{setIsLoading(false)}}/>
            }
          </div>
          <span>Original</span>
          <h2 className='font-bold text-2xl sm:text-3xl'>MY RANDOM TITLE</h2>

          <div className='flex flex-col gap-y-3 items-center mt-6'>
            <div className='hover:cursor-pointer transform hover:scale-105 rounded flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-[#D1415A]'>
              <FiDownload className="text-[27px] sm:text-[27px]" />
              <span>DOWNLOAD</span>
            </div>
            <div className='flex flex-col sm:flex-row gap-x-10 w-full gap-y-3'>
              <div className='hover:cursor-pointer transform hover:scale-105 rounded flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500'>
                <FiInstagram className="text-[27px] sm:text-[27px]" />
                <span>SHARE</span>
              </div>
              <div className='hover:cursor-pointer transform hover:scale-105 rounded flex flex-row items-center gap-x-4 py-2 pl-6 pr-6 text-white font-semibold bg-blue-500'>
                <FiFacebook className="text-[27px] sm:text-[27px]" />
                <span>SHARE</span>
              </div>
            </div>
          </div>
        </section>

        {isLoading && <div className='flex items-center justify-center w-screen h-full bg-white absolute top-24 sm:top-32 z-100 p-1'>
          <AiOutlineLoading3Quarters size={90} className="text-cetys-yellow animate-spin"/>
        </div>}
      </main>

      <Footer />


      
    </div>
  )
}
