import Head from 'next/head'
import Header from '../components/header';
import Footer from '../components/footer';

export default function Home() {
  return (
    <div className='flex flex-col min-h-screen justify-between bg-fox-pattern'>
      <Head>
        <title>My Foxy Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className='flex flex-col w-full items-center'>
        <div className='relative'>
          <h1 className='font-bold text-2xl mb-9 square-decoration'>IMAGE GENERATOR</h1>
        </div>
        <section className='flex flex-row gap-x-10 items-center justify-start'>
          <div className='flex flex-col items-start'>
            <p className='font-bold text-xl'>INTRODUCE YOUR SEARCH</p>
            <input type="text" className='border-2 outline-0 w-[30rem] px-3 py-1 my-1 text-xl focus:border-cetys-yellow'/>
            <p>An unique result each time</p>

            <button className='text-xl font-semibold bg-anemia-yellow px-6 py-1 rounded-sm mt-6 transform hover:scale-105'>
              GENERATE MY FOXY IMAGE
            </button>
          </div>
          <img width={300} src='https://images-assets.nasa.gov/image/PIA12229/PIA12229~thumb.jpg'/>
        </section>
      </main>

      <Footer />
    </div>
  )
}
